name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.2.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm lint

      - name: Test
        # Will run the step even if lint step failed
        if: success() || failure()
        run: pnpm run test
        env:
          CI: true

      - name: Typecheck
        # Will run the step even if lint step failed
        if: success() || failure()
        run: pnpm run typecheck
